AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for an S3 backed website.

Outputs:
  Arn:
    Description: Arn of the bucket
    Value: !GetAtt [ Website, Arn ]
    Export:
      Name: !Sub ${AWS::StackName}-Arn
  # See https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#aws-resource-s3-bucket-example1.yaml
  WebsiteURL:
    Description: URL of the website
    Value: !GetAtt [ Website, WebsiteURL ]
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteURL
  WebsiteSecureURL:
    Value: !Join [ "", [ "https://", !GetAtt [ Website, DomainName ] ] ]
    Description: Name of S3 bucket to hold website content
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteSecureURL

Parameters:
  BucketName:
    Type: String
    Description: Name of the bucket
    MinLength: 3
    MaxLength: 59


Resources:

  # Bucket for the static website content
  # See https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  Website:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      LoggingConfiguration:
        DestinationBucketName: !Sub ${BucketName}-sal

  # Bucket for the Server Access Logs
  # See https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerLogs.html
  AccessLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketName}-sal
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - Id: Archive and purge
            Status: Enabled
            ExpirationInDays: 180
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
